# Generated by Django 3.2.5 on 2021-08-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_post_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upload_at',
            new_name='update_at',
        ),
    ]
